server:
  port: 9090
spring:
  application:
    name: purchase-cart
  datasource:
    url: jdbc:h2:file:./data
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    open-in-view: true